steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "kelompok-03-vm-1"
      - "--zone=asia-southeast2-a"
      - "--command=sudo bash /var/www/html/contact-book/deploy.sh"

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY
